spring:
  cloud:
    consul:
      port: 8500
      host: 172.16.2.103
      discovery:
        prefer-ip-address: true
        ip-address: 172.16.4.6
  sleuth:
    baggage-keys:
      - SessionId

logging:
  level:
    root: INFO
    #org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG