spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://www.baidu.com/
          predicates:
            - After=2020-10-16T14:30:23.079+08:00[Asia/Shanghai]
          order: 10