server:
  port: 8080


spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: query
  cloud:
    gateway:
      routes:
        - id: jd_route
          uri: http://www.jd.com/
          predicates:
            - Path=/jd
          order: 0
        - id: baidu_route
          uri: http://www.baidu.com/
          predicates:
            - Path=/baidu
          order: 1
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
